
pool:
  vmImage: 'windows-latest'

steps:
  - task: PowerShell@2
    displayName: 'Deploy Frontdoor origins'
    AzureSubscription: ''
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\Deploy\Powershell\Start-FrontdoorOriginDeployment.ps1
      arguments: >
        -TemplateFile '$(System.DefaultWorkingDirectory)\Deploy\BICEP\FrontDoorOrigin.bicep'
        -CosmosName 'ddb-cosmos'
        -CosmosDatabase 'ApiDatabase'
        -CosmosContainer 'WafRules'